spring:
  application:
    name: monitor-service
  datasource:
    url: jdbc:mysql://39.101.132.xx:3306/ykk?useUnicode=true&autoReconnect=true&autoReconnectForPools=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: xx
    password: xx
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 39.101.132.xx
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 5
        min-idle: 1
      shutdown-timeout: 100
    timeout: 1000
    password:


elasticsearch:
  rest:
    uris: http://39.101.132.xxx:9200


server:
  port: 8001